/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedAccountsIndexRouteImport } from './routes/_authed/accounts/index'
import { Route as AuthedAccountsIdRouteImport } from './routes/_authed/accounts/$id'
import { Route as AuthedBudgetsIndexRouteImport } from './routes/_authed/budgets/index'
import { Route as AuthedPayorsIndexRouteImport } from './routes/_authed/payors/index'
import { Route as AuthedPayorsIdRouteImport } from './routes/_authed/payors/$id'
import { Route as AuthedTransactionsIndexRouteImport } from './routes/_authed/transactions/index'
import { Route as AuthedTransactionsIdRouteImport } from './routes/_authed/transactions/$id'
import { Route as AuthedTransactionsNewRouteImport } from './routes/_authed/transactions/new'
import { Route as AuthedVendorsIndexRouteImport } from './routes/_authed/vendors/index'
import { Route as AuthedVendorsIdRouteImport } from './routes/_authed/vendors/$id'
import { Route as AuthedBudgetsBudgetIdIndexRouteImport } from './routes/_authed/budgets/$budgetId/index'
import { Route as AuthedBudgetsNewIndexRouteImport } from './routes/_authed/budgets/new/index'
import { Route as AuthedBudgetsNewLiteRouteImport } from './routes/_authed/budgets/new/lite'
import { Route as AuthedBudgetsBudgetIdItemsItemIdRouteImport } from './routes/_authed/budgets/$budgetId/items/$itemId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsIndexRoute = AuthedAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsIdRoute = AuthedAccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBudgetsIndexRoute = AuthedBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPayorsIndexRoute = AuthedPayorsIndexRouteImport.update({
  id: '/payors/',
  path: '/payors/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPayorsIdRoute = AuthedPayorsIdRouteImport.update({
  id: '/payors/$id',
  path: '/payors/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsIndexRoute = AuthedTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsIdRoute = AuthedTransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsNewRoute = AuthedTransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVendorsIndexRoute = AuthedVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVendorsIdRoute = AuthedVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBudgetsBudgetIdIndexRoute =
  AuthedBudgetsBudgetIdIndexRouteImport.update({
    id: '/budgets/$budgetId/',
    path: '/budgets/$budgetId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBudgetsNewIndexRoute = AuthedBudgetsNewIndexRouteImport.update({
  id: '/budgets/new/',
  path: '/budgets/new/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBudgetsNewLiteRoute = AuthedBudgetsNewLiteRouteImport.update({
  id: '/budgets/new/lite',
  path: '/budgets/new/lite',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBudgetsBudgetIdItemsItemIdRoute =
  AuthedBudgetsBudgetIdItemsItemIdRouteImport.update({
    id: '/budgets/$budgetId/items/$itemId',
    path: '/budgets/$budgetId/items/$itemId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile': typeof AuthedProfileRoute
  '/reports': typeof AuthedReportsRoute
  '/accounts/$id': typeof AuthedAccountsIdRoute
  '/payors/$id': typeof AuthedPayorsIdRoute
  '/transactions/$id': typeof AuthedTransactionsIdRoute
  '/transactions/new': typeof AuthedTransactionsNewRoute
  '/vendors/$id': typeof AuthedVendorsIdRoute
  '/accounts/': typeof AuthedAccountsIndexRoute
  '/budgets/': typeof AuthedBudgetsIndexRoute
  '/payors/': typeof AuthedPayorsIndexRoute
  '/transactions/': typeof AuthedTransactionsIndexRoute
  '/vendors/': typeof AuthedVendorsIndexRoute
  '/budgets/new/lite': typeof AuthedBudgetsNewLiteRoute
  '/budgets/$budgetId/': typeof AuthedBudgetsBudgetIdIndexRoute
  '/budgets/new/': typeof AuthedBudgetsNewIndexRoute
  '/budgets/$budgetId/items/$itemId': typeof AuthedBudgetsBudgetIdItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile': typeof AuthedProfileRoute
  '/reports': typeof AuthedReportsRoute
  '/': typeof AuthedIndexRoute
  '/accounts/$id': typeof AuthedAccountsIdRoute
  '/payors/$id': typeof AuthedPayorsIdRoute
  '/transactions/$id': typeof AuthedTransactionsIdRoute
  '/transactions/new': typeof AuthedTransactionsNewRoute
  '/vendors/$id': typeof AuthedVendorsIdRoute
  '/accounts': typeof AuthedAccountsIndexRoute
  '/budgets': typeof AuthedBudgetsIndexRoute
  '/payors': typeof AuthedPayorsIndexRoute
  '/transactions': typeof AuthedTransactionsIndexRoute
  '/vendors': typeof AuthedVendorsIndexRoute
  '/budgets/new/lite': typeof AuthedBudgetsNewLiteRoute
  '/budgets/$budgetId': typeof AuthedBudgetsBudgetIdIndexRoute
  '/budgets/new': typeof AuthedBudgetsNewIndexRoute
  '/budgets/$budgetId/items/$itemId': typeof AuthedBudgetsBudgetIdItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/accounts/$id': typeof AuthedAccountsIdRoute
  '/_authed/payors/$id': typeof AuthedPayorsIdRoute
  '/_authed/transactions/$id': typeof AuthedTransactionsIdRoute
  '/_authed/transactions/new': typeof AuthedTransactionsNewRoute
  '/_authed/vendors/$id': typeof AuthedVendorsIdRoute
  '/_authed/accounts/': typeof AuthedAccountsIndexRoute
  '/_authed/budgets/': typeof AuthedBudgetsIndexRoute
  '/_authed/payors/': typeof AuthedPayorsIndexRoute
  '/_authed/transactions/': typeof AuthedTransactionsIndexRoute
  '/_authed/vendors/': typeof AuthedVendorsIndexRoute
  '/_authed/budgets/new/lite': typeof AuthedBudgetsNewLiteRoute
  '/_authed/budgets/$budgetId/': typeof AuthedBudgetsBudgetIdIndexRoute
  '/_authed/budgets/new/': typeof AuthedBudgetsNewIndexRoute
  '/_authed/budgets/$budgetId/items/$itemId': typeof AuthedBudgetsBudgetIdItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/reports'
    | '/accounts/$id'
    | '/payors/$id'
    | '/transactions/$id'
    | '/transactions/new'
    | '/vendors/$id'
    | '/accounts/'
    | '/budgets/'
    | '/payors/'
    | '/transactions/'
    | '/vendors/'
    | '/budgets/new/lite'
    | '/budgets/$budgetId/'
    | '/budgets/new/'
    | '/budgets/$budgetId/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/reports'
    | '/'
    | '/accounts/$id'
    | '/payors/$id'
    | '/transactions/$id'
    | '/transactions/new'
    | '/vendors/$id'
    | '/accounts'
    | '/budgets'
    | '/payors'
    | '/transactions'
    | '/vendors'
    | '/budgets/new/lite'
    | '/budgets/$budgetId'
    | '/budgets/new'
    | '/budgets/$budgetId/items/$itemId'
  id:
    | '__root__'
    | '/_authed'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/profile'
    | '/_authed/reports'
    | '/_authed/'
    | '/_authed/accounts/$id'
    | '/_authed/payors/$id'
    | '/_authed/transactions/$id'
    | '/_authed/transactions/new'
    | '/_authed/vendors/$id'
    | '/_authed/accounts/'
    | '/_authed/budgets/'
    | '/_authed/payors/'
    | '/_authed/transactions/'
    | '/_authed/vendors/'
    | '/_authed/budgets/new/lite'
    | '/_authed/budgets/$budgetId/'
    | '/_authed/budgets/new/'
    | '/_authed/budgets/$budgetId/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts/': {
      id: '/_authed/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthedAccountsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts/$id': {
      id: '/_authed/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthedAccountsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/budgets/': {
      id: '/_authed/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof AuthedBudgetsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payors/': {
      id: '/_authed/payors/'
      path: '/payors'
      fullPath: '/payors/'
      preLoaderRoute: typeof AuthedPayorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payors/$id': {
      id: '/_authed/payors/$id'
      path: '/payors/$id'
      fullPath: '/payors/$id'
      preLoaderRoute: typeof AuthedPayorsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions/': {
      id: '/_authed/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthedTransactionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions/$id': {
      id: '/_authed/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthedTransactionsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions/new': {
      id: '/_authed/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AuthedTransactionsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vendors/': {
      id: '/_authed/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthedVendorsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vendors/$id': {
      id: '/_authed/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AuthedVendorsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/budgets/$budgetId/': {
      id: '/_authed/budgets/$budgetId/'
      path: '/budgets/$budgetId'
      fullPath: '/budgets/$budgetId/'
      preLoaderRoute: typeof AuthedBudgetsBudgetIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/budgets/new/': {
      id: '/_authed/budgets/new/'
      path: '/budgets/new'
      fullPath: '/budgets/new/'
      preLoaderRoute: typeof AuthedBudgetsNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/budgets/new/lite': {
      id: '/_authed/budgets/new/lite'
      path: '/budgets/new/lite'
      fullPath: '/budgets/new/lite'
      preLoaderRoute: typeof AuthedBudgetsNewLiteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/budgets/$budgetId/items/$itemId': {
      id: '/_authed/budgets/$budgetId/items/$itemId'
      path: '/budgets/$budgetId/items/$itemId'
      fullPath: '/budgets/$budgetId/items/$itemId'
      preLoaderRoute: typeof AuthedBudgetsBudgetIdItemsItemIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAccountsIdRoute: typeof AuthedAccountsIdRoute
  AuthedPayorsIdRoute: typeof AuthedPayorsIdRoute
  AuthedTransactionsIdRoute: typeof AuthedTransactionsIdRoute
  AuthedTransactionsNewRoute: typeof AuthedTransactionsNewRoute
  AuthedVendorsIdRoute: typeof AuthedVendorsIdRoute
  AuthedAccountsIndexRoute: typeof AuthedAccountsIndexRoute
  AuthedBudgetsIndexRoute: typeof AuthedBudgetsIndexRoute
  AuthedPayorsIndexRoute: typeof AuthedPayorsIndexRoute
  AuthedTransactionsIndexRoute: typeof AuthedTransactionsIndexRoute
  AuthedVendorsIndexRoute: typeof AuthedVendorsIndexRoute
  AuthedBudgetsNewLiteRoute: typeof AuthedBudgetsNewLiteRoute
  AuthedBudgetsBudgetIdIndexRoute: typeof AuthedBudgetsBudgetIdIndexRoute
  AuthedBudgetsNewIndexRoute: typeof AuthedBudgetsNewIndexRoute
  AuthedBudgetsBudgetIdItemsItemIdRoute: typeof AuthedBudgetsBudgetIdItemsItemIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAccountsIdRoute: AuthedAccountsIdRoute,
  AuthedPayorsIdRoute: AuthedPayorsIdRoute,
  AuthedTransactionsIdRoute: AuthedTransactionsIdRoute,
  AuthedTransactionsNewRoute: AuthedTransactionsNewRoute,
  AuthedVendorsIdRoute: AuthedVendorsIdRoute,
  AuthedAccountsIndexRoute: AuthedAccountsIndexRoute,
  AuthedBudgetsIndexRoute: AuthedBudgetsIndexRoute,
  AuthedPayorsIndexRoute: AuthedPayorsIndexRoute,
  AuthedTransactionsIndexRoute: AuthedTransactionsIndexRoute,
  AuthedVendorsIndexRoute: AuthedVendorsIndexRoute,
  AuthedBudgetsNewLiteRoute: AuthedBudgetsNewLiteRoute,
  AuthedBudgetsBudgetIdIndexRoute: AuthedBudgetsBudgetIdIndexRoute,
  AuthedBudgetsNewIndexRoute: AuthedBudgetsNewIndexRoute,
  AuthedBudgetsBudgetIdItemsItemIdRoute: AuthedBudgetsBudgetIdItemsItemIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
